### ISSUE TITLE
How often do you update the translation pages？

### ISSUE THREAD

**Issue by tangdou1** [godotengine/godot-docs-l10n#2]

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot-docs-l10n/commits/master

**Comment by nitramr** [comment]
@akien-mga it would be great if an admin could synchronize that latest Weblate translations with that repository. The last sync is more than 3 months old.

For me, it is confusing because I'm checking the online documentation to find untranslated paragraphs or spelling mistakes to fix them in Weblate, but often it is already done there.
